all: build install

build:
	xbuild Protractor2.csproj

install:
	cp bin/Debug/Protractor2.dll ./Output/Protractor2/Plugins/
	cp Protractor2.version ./Output/Protractor2/
	cp LICENSE ./Output/Protractor2/
	cp gpl.txt ./Output/Protractor2/
	cp mit.txt ./Output/Protractor2/
